name: build
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cmake_extra: "-DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON"
          - os: ubuntu-22.04
            cmake_extra: "-DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON"
          - os: ubuntu-20.04
            cmake_extra: "-DCPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON"
          - os: macos-latest
            cmake_extra: ""
          - os: windows-latest
            cmake_extra: "-T v142,host=x86"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt install qtbase5-dev
        if: ${{ matrix.os == 'ubuntu-20.04' }}
      - run: sudo apt install qt6-base-dev freeglut3-dev
        if: ${{ matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-latest' }}
      - uses: jurplel/install-qt-action@v3
        with:
          version: "6.4.0"
          arch: "win64_msvc2019_64"
        if: ${{ matrix.os == 'windows-latest' }}
      - run: brew install qt
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Configure CMake
        run: |
          cmake --version
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install \
            -DCPACK_PACKAGE_DIRECTORY=${PWD}/package \
            -DBUILD_LIBLSL_FROM_SOURCE=ON \
            ${{ matrix.cmake_extra }}
          cmake -DLSL_UNIXFOLDERS=ON build
      - run: cmake --build build --config Release -j --target install
      - name: Package
        run: |
          export LD_LIBRARY_PATH=$Qt5_DIR/lib:$Qt6_DIR/lib:$LD_LIBRARY_PATH
          cmake --build build --config Release -j --target package
          cmake -E remove_directory package/_CPack_Packages
      - uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ matrix.os }}
          path: package/LabRecorder*
